### ISSUE TITLE
epic: unitest for cortex cpp

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1069]
We need create unitest for done ticket. For now we will use [Gtest](https://github.com/google/googletest) to write unitest

Unitest can run locally and add to CI pipeline
When building  debug mode will include test, release wont including it 
Subtask:
- [x] Cmake build test option
- [ ] CI build and run unitest (Need dev ops)
- [ ] Unitest for utils folder
- [ ] Unitest for commands  
- [ ] Unitest for sever service
     - [ ] models services
          - [ ] model pull
          - [ ] model start
          - [ ] model stop
          - [ ] model list
          - [ ] model get
     - [ ] engines services
          - [ ] engine install
          - [ ] engine list
          - [ ] engine get 
     - [ ] chat services
          - [ ] stream chat
          - [ ] non stream chat 
- [ ] Unitest for engines 
     - [ ] llamacpp
     - [ ] tensorrt-llm
     - [ ] onnx

**Comment by nguyenhoangthuan99** [comment]
Update:
- under development in this branch https://github.com/janhq/cortex/tree/feat-background-process-server/engine/test
- when build add an option to decide build test or not: `cmake .. -DCMAKE_BUILD_TEST=ON` [source code](https://github.com/janhq/cortex/blob/feat-background-process-server/engine/CMakeLists.txt#L84) here. Default is `OFF` -> no build test

**Comment by dan-menlo** [comment]
@namchuai @vansangpfiev Can we break this down into smaller epics, otherwise this is a task that never gets closed
