### ISSUE TITLE
epic: `cortex engines` commands

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1072]
# Goal 
- Cortex can install engines (e.g. llama.cpp, tensorrt-llm)
- Strong error recovery

## Spec
- [x] https://github.com/janhq/cortex/issues/1046

### Install (this issue)
- [x] HTTP API support for cortex engines install
- [x] CLI support for `cortex engines <name (cortex.llamacpp/cortex.tensorrt-llm/cortex.onnx)> install`
- [x] Downloading and unzip engine file (currently store engine to `engines/<engine>`)
- [x] Downloading and unzip cuda toolkit (if needed - because, e.g. macos does not need this)
- [x] Libcurl https://github.com/janhq/cortex.cpp/pull/1179
- [x] Hardware detection
    - [x] AVX information 
    - [x] OS
    - [x] CPU arch
    - [x] GPU driver version
### Engines list
- [x] https://github.com/janhq/cortex.cpp/issues/1074
### Engines get
- [x] https://github.com/janhq/cortex.cpp/issues/1073
### Uninstall 
- [x] https://github.com/janhq/cortex.cpp/issues/1088
### Dependency Packing
- [x] #1085 
- [x] https://github.com/janhq/cortex.cpp/issues/1047

## Outstanding / Bugs:
- [x] #1168 

## Some resources
[Nvidia Support Matrix](https://docs.nvidia.com/deeplearning/cudnn/latest/reference/support-matrix.html#gpu-cuda-toolkit-and-cuda-driver-requirements)
[CUDA Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/#id1)

**Comment by namchuai** [comment]
@vansangpfiev @nguyenhoangthuan99 , please add if I missing any. Thank you 🙏

**Comment by dan-menlo** [comment]
@namchuai Can I clarify a few things: 

- CLI command: is it `install` or `init`? If `install`, let's change this issue name
- Will we do an `uninstall` command as well?

**Comment by dan-menlo** [comment]
@namchuai Another thought is, should the command be:

```
cortex engines install tensorrt-llm
or 
cortex engines tensorrt-llm install
```

I had originally gone with `cortex engines tensorrt-llm install`, because I initially thought that each of the engines would eventually expose its own CLI commands, e.g: 

```
cortex engines tensorrt-llm settings ...
cortex engines tensorrt-llm gpu 2
```

However, I realize that `install` is an action on `engines`, rather than `tensorrt-llm` (or engine name). In this case, the correct approach should be: 

```
cortex engines install tensorrt-llm
cortex engines uninstall tensorrt-llm
cortex engines list
```

**Comment by namchuai** [comment]
> @namchuai Can I clarify a few things:
> 
> * CLI command: is it `install` or `init`? If `install`, let's change this issue name
> * Will we do an `uninstall` command as well?

1. Yes, it's `install`. I updated the title.
2. I agree about `uninstall`
cc @vansangpfiev @nguyenhoangthuan99 , what do you think?

**Comment by namchuai** [comment]
> @namchuai Another thought is, should the command be:
> 
> ```
> cortex engines install tensorrt-llm
> or 
> cortex engines tensorrt-llm install
> ```
> 
> I had originally gone with `cortex engines tensorrt-llm install`, because I initially thought that each of the engines would eventually expose its own CLI commands, e.g:
> 
> ```
> cortex engines tensorrt-llm settings ...
> cortex engines tensorrt-llm gpu 2
> ```
> 
> However, I realize that `install` is an action on `engines`, rather than `tensorrt-llm` (or engine name). In this case, the correct approach should be:
> 
> ```
> cortex engines install tensorrt-llm
> cortex engines uninstall tensorrt-llm
> cortex engines list
> ```

IMHO, 2nd option is more natural to me.
```
$ cortex engines install tensorrt-llm
```
And I think we should support `options` if any, for example:
```
$ cortex engines install cortex.llamacpp --vulkan 1
```

**Comment by vansangpfiev** [comment]
> > @namchuai Can I clarify a few things:
> > 
> > * CLI command: is it `install` or `init`? If `install`, let's change this issue name
> > * Will we do an `uninstall` command as well?
> 
> 1. Yes, it's `install`. I updated the title.
> 2. I agree about `uninstall`
>    cc @vansangpfiev @nguyenhoangthuan99 , what do you think?

I agree, we should support `uninstall`. @namchuai Can you please create a ticket for it?

**Comment by gabrielle-ong** [comment]
Closing this Epic 🌮 🎉  Thanks @vansangpfiev @namchuai!
