### ISSUE TITLE
epic: `cortex models pull <ID_or_URL>`

### ISSUE THREAD

**Issue by Van-QA** [janhq/cortex.cpp#1077]
## Goal

- Pull from Jan's curated models 
- Pull from Huggingface based on URL 

## Tasklist

- [x] https://github.com/janhq/cortex.cpp/issues/1004
- [x] https://github.com/janhq/cortex.cpp/issues/1006
- [x] https://github.com/janhq/cortex.cpp/issues/777

## Bugs
- [x] https://github.com/janhq/cortex.cpp/issues/1017
- [x] https://github.com/janhq/cortex.cpp/issues/1139
- [x] #1344 
- [x] https://github.com/janhq/cortex.cpp/issues/1010 (API server process crash edge case)
- [x] [#777](https://github.com/janhq/cortex.cpp/issues/777)

## Out-of-scope

- Pause Functionality https://github.com/janhq/jan/issues/3519 (likely Sprint 21)
- Multi-mirror? (e.g. if HF down)
- Built in models to move back to Jan huggingface? (i.e. update URL)

**Comment by dan-menlo** [comment]
@namchuai Can I check, does your implementation of `cortex pull` cover the case of a Huggingface URL to a specific GGUF model?

```
cortex pull https://huggingface.co/BafS/gemma-2-2b-it-Q4_K_M-GGUF/blob/main/gemma-2-2b-it-q4_k_m.gguf
```

**Comment by dan-menlo** [comment]
> After downloading model, should we automatically check for engine and init engine (if neccessary)?

@namchuai From a UX perspective, I think we should not automatically init a model:

- We should show useful feedback to pre-empt problems
- e.g. "To run this model, you will need to initialize the TensorRT-LLM engine, i.e. `cortex engines init tensorrt-llm`

**Comment by namchuai** [comment]
> @namchuai Can I check, does your implementation of `cortex pull` cover the case of a Huggingface URL to a specific GGUF model?
> 
> ```
> cortex pull https://huggingface.co/BafS/gemma-2-2b-it-Q4_K_M-GGUF/blob/main/gemma-2-2b-it-q4_k_m.gguf
> ```

Currently, we are not cover this case. This will be supported in upcoming release, I think.

**Comment by gabrielle-ong** [comment]
Adding a bug with `cortex pull` (and also `cortex run`) - 
`Re-download? n` -> still triggers `re-download` again
#1344

**Comment by gabrielle-ong** [comment]
Marking as complete! 🎉
