### ISSUE TITLE
epic: Cortex.cpp CLI MVP v0.1

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1081]
This ticket only includes command list, the actual callback for each command will be in sub-tickets.

## Architecture

- https://github.com/CLIUtils/CLI11 can be a good library: header only, no dependencies, c++11.

## Installation, Updating & Uninstallation

- #1030 
- uninstall
- #1087 

## Process

- https://github.com/janhq/cortex.cpp/pull/1043

## Engine Management

- [x] janhq/cortex#1072
- [x] janhq/cortex#1074
- [x] janhq/cortex#1073

## Hardware Management

- https://github.com/janhq/cortex.cpp/issues/1068

## Model Management

- [x] janhq/cortex#1075
- [x] janhq/cortex#1064
- [ ] janhq/cortex#1060
- https://github.com/janhq/cortex.cpp/issues/1078

## Model Running

- [x] janhq/cortex#1076
- [x] #1204

## Basic Use

- [x] Chat
- [ ] embeddings 

## System

- [x] janhq/cortex#1066
- [x] ps
- [x] #1205

## Logs

Logs turned out to be more work than we thought, due to Windows having file perm issues and requiring us to implement Unix Daemon Sockets

- https://github.com/janhq/cortex.cpp/issues/1054
- https://github.com/janhq/cortex.cpp/issues/1056

## Packaging

- [ ] Docker template

List of commands:

## Unknown? 

- [x] janhq/cortex.cpp#29
- [x] janhq/cortex.cpp#31
- [x] janhq/cortex.cpp#41
- [x] janhq/cortex.cpp#32
- [x] janhq/cortex.cpp#37

**Comment by freelerobot** [comment]
@vansangpfiev, this is really helpful. 
Lets track in specs instead: https://github.com/janhq/cortex.cpp/discussions/1109
I've migrated your list over 🙏

**Comment by dan-menlo** [comment]
@vansangpfiev I spoke to Nicole, I think this is better positioned as an epic that covers the Cortex CLI MVP scope.
We will keep this open for now (it will move to Sprint 20)

**Comment by gabrielle-ong** [comment]
Closing this HUGE EPIC - thanks Team! @vansangpfiev @namchuai @nguyenhoangthuan99
