### ISSUE TITLE
epic: Cortex TensorRT-LLM support

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1152]
## Goal 

- `cortex run model:tensorrt-llm`
- Support TensorRT-LLM model and inference params
- Support advanced params (e.g. batching)

## Enables

- Jan supports TensorRT-LLM

## Tasklist

- [x] https://github.com/janhq/cortex.cpp/issues/1020
- [ ] https://github.com/janhq/cortex.tensorrt-llm/issues/27
- [x] https://github.com/janhq/cortex.tensorrt-llm/issues/29
- [ ] Interrupt inference https://github.com/janhq/cortex.tensorrt-llm/issues/31
- [ ] `cortex ps`
- [ ] System Monitor shows VRAM usage? 
- [x] https://github.com/janhq/cortex.tensorrt-llm/issues/31

**Comment by dan-menlo** [comment]
Deprecated due to TensorRT-LLM not supporting Desktop
