### ISSUE TITLE
epic: Jan and Cortex's Built-in Model Library has latest models + pipeline

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/cortex.cpp#1155]
## Goal

- Built-in model library has curated `model.yaml` with best parameters
- Aim for a best-in-class user experience that 
- Include system prompts that provide good experience? (may be anti-pattern)

## Decisions
- https://github.com/janhq/cortex.cpp/discussions/1178

### Model Library
- [ ] Work with eng team to update URLs
- [ ] Update READMEs
- [ ] Provide more quantizations (e.g. full llama.cpp quantizations)
- [ ] Document how to create/add a Model Library 
- [x] https://github.com/janhq/cortex.so/issues/78
- [ ] [TBD] Shift Built-in model repos back to Jan's huggingface (better brand recognition, we are also not pushing Cortex as a brand for now)

### Models

- [ ] https://github.com/janhq/cortex.cpp/issues/1182
- [ ] https://github.com/janhq/cortex.cpp/issues/1181
- [ ] https://github.com/janhq/cortex.cpp/issues/1180

### Model Compilation Pipeline
- [ ] Update Model compilation Infra
- [ ] Is there a way for us to "queue" up models?

## Future Roadmap

- Model Recommendations: can we consider recommending bigger models (e.g. q8) if hardware is strong?

**Comment by nguyenhoangthuan99** [comment]
## Objectives
1. Implement model quantization
2. Update `model.yaml` for three models
3. Organize branch structure as per discussion #1154

## Quantization Strategy
- Each quantization will be tagged in Hugging Face repo, e.g., `8b-gguf-q4-km`
- This approach will:
     - Facilitate easier management of models from cortex.cpp
     - Simplify model downloading and execution commands

## Example Command
```
cortex pull llama3.1:8b-gguf-q4-km
cortex run llama3.1:8b-gguf-q4-km
```
This concise command provides sufficient information for users.

## Tasks
1. [ ] Develop CI runner for building all quantization for each model:
     - Download from original source
     - Convert to GGUF format
     - Perform quantization
     - Update Hugging Face repository

2. [ ] Create script to update `model.yaml` for models:
     - Update default parameters
     - Update system prompts

This approach will streamline model management and improve user experience when working with cortex.cpp.

**Comment by nguyenhoangthuan99** [comment]
The 2 CI pipelines in this [PR](https://github.com/janhq/cortex.llamacpp/pull/231) can help solve this problem

**CI convert and quantization**
Steps:
- Get inputs: 
     - source hugging face model repo (e.g.meta-llama/Meta-Llama-3.1-8B-Instruct)
     - source model size (e.g. 8b)
     - target model id: target model repo_id in cortexso/janhq to push (e.g. llama3.1)
     - quantization level: (e.g., 'q4-km') or 'all' for all levels. Currently, we support ('q2-k', “q3-ks”, “q3-km” ,”q3-kl” ,”q4-ks”, “q4-km” ,”q5-ks” ,”q5-km”, ”q6-k”, “q8-0”)
- Download source model repo if it doesn't exist.
- Convert source model repo to gguf format
- Quantize the gguf format to input quantization level
- Upload quantized model to target model repo with correct branch

After uploaded successfully, the model repo will add new tag like this llama3 repo https://huggingface.co/cortexso/llama3/tree/main
![Image](https://github.com/user-attachments/assets/5a28fb42-fa2c-423a-a53f-bf7346876887)

**CI update model.yml**
- Get inputs: 
     - the 'key=value' pairs that you want to update, separated by space
     - source model size (e.g. 8b)
     - target model id: target model repo_id in cortexso/janhq to push (e.g. llama3.1)
     - quantization level: (e.g., 'q4-km') or 'all' for all levels. Currently, we support ('q2-k', “q3-ks”, “q3-km” ,”q3-kl” ,”q4-ks”, “q4-km” ,”q5-ks” ,”q5-km”, ”q6-k”, “q8-0”)
- Prepare environments
- Run script to update model.yml for target quantization level and target model repo_id.
- Upload updated model.yml to hugging face.

**Comment by nguyenhoangthuan99** [comment]
To use this pipeline:
- Go to https://github.com/janhq/cortex.llamacpp/actions
- Select the `Convert model to gguf with specified quant` workflow inside the action tab
![Image](https://github.com/user-attachments/assets/5fad36a2-cab1-4dcc-ba82-4ea0ffadf88b)

- Click on `Run workflow` 
![Image](https://github.com/user-attachments/assets/2ecf4b12-faf1-4426-bed1-cc6055100334)
And input all parameters
![Image](https://github.com/user-attachments/assets/a908d095-18b6-40f8-9e5a-c4954d92bd23)
Note that the `Target HuggingFace model ID to push` is cortexso model repo, in my example it is [llama3](https://huggingface.co/cortexso/llama3/tree/main) 

- After click run, go to tab `Action` and we can see the workflow is running 
![Image](https://github.com/user-attachments/assets/df67630e-0f21-4c89-8de1-175b1d754a95)
![Image](https://github.com/user-attachments/assets/84056de9-ca3e-4fca-8190-b8277947ac64)

- When the CI finish running, we can go to the cortex so repo https://huggingface.co/cortexso/llama3, to check if the model is updated

**Comment by dan-homebrew** [comment]
@nguyenhoangthuan99 I am refactoring the "Built-in Model Library" to a separate epic. Let's focus this epic on the Model Converter Pipeline.

**Comment by hiento09** [comment]
Infra:
- [ ] GitHub Actions grants runner group permission for the repo `janhq/models`
- [ ] GitHub Actions grants secret permission for the repo `janhq/models`

**Comment by nguyenhoangthuan99** [comment]
I add the updated model converter pipeline to [janhq/models](https://github.com/janhq/models/actions) repo. And also add a pipeline to automatically update the model.yml file in hugging face cc @gabrielle-ong, now we can run CI pipeline in this repo.

Guild for update `model.yml` file

1. Click to `Update model.yml with specific quant` 
![Image](https://github.com/user-attachments/assets/1808e9a7-a24b-44c1-a1ea-3c1c0484b3fd)
2. Click run workflow
![Image](https://github.com/user-attachments/assets/4985b24f-04ea-4099-8bcd-a20c5805d4c2)

Please update with the format
`"top_p=0.9" "top_k=40" "stop=['<|end_of_text|>', '<|eot_id|>']"`

Note that the `prompt_template` field should not update this way because this field sometimes cannot handle proper special character on string.
