### ISSUE TITLE
Cortex JS Client

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1162]
## Overview

- Strong client support for Cortex
- Client libaries should support model loading, unloading

## Tasklist

- [ ] cortex.js Github README
- [ ] cortex.py Github README
- [ ] All model methods supported

**Comment by freelerobot** [comment]
Prerequisite for Jan to port over
