### ISSUE TITLE
epic: llama.cpp should support `LLVM` for ARM-based CPUs

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1251]
## Goal 

- llama.cpp should support LLVM for ARM-based CPUs

## Tasklist

- [ ] What should be the hardware heuristic to opt for LLVM?
- [ ] Should Installer support this? 
- [ ] This may require us to have `cortex engines` be able to define a "default" llama.cpp version (if two or more exist)

**Comment by dan-menlo** [comment]
@eckartal Can you link the Reddit post here (and any other requests for this?)

**Comment by eckartal** [comment]
> @eckartal Can you link the Reddit post here (and any other requests for this?)

![image](https://github.com/user-attachments/assets/fc43b277-8797-4898-a0db-5013daf20d23)

Source: https://www.reddit.com/r/LocalLLaMA/comments/1fjpm7j/jan_now_runs_faster_on_cpus/

**Comment by dan-menlo** [comment]
Closing to handle as part of #1453
