### ISSUE TITLE
epic: llama.cpp should support `sycl` for Intel-based CPUs

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1252]
## Goal 

- Should support `sycl` for Intel-based CPUs

## Tasklist

- [ ] What should be the hardware heuristic to opt for LLVM?
- [ ] Should Installer support this? 
- [ ] This may require us to have `cortex engines` be able to define a "default" llama.cpp version (if two or more exist)

**Comment by dan-menlo** [comment]
Closing to handle as part of #1453
