### ISSUE TITLE
epic: Release beta/stable on Github and Website

### ISSUE THREAD

**Issue by freelerobot** [janhq/cortex.cpp#1330]
Goal: v1.0.0 release on 7 Oct 2024 🎉 

**Problem**
- Users are still downloading old Cortexjs from our site and Github
- They are filling bugs bc it doesn't work

**Success Criteria**
- Once we're ready to release cortex v0.1
- [ ] Release stable on Github releases
- [ ] Release stable on cortex.so website

**Discussion**
- Where are nightly releases getting distributed? - Discord #cortex-nightly, Github
- Where are beta releases getting distributed? - Github

**Tasklist**
- [ ] Download proxy on README, similar to jan app

**Comment by gabrielle-ong** [comment]
Discussed with @dan-homebrew
- Website and Github will focus on full/universal installer 
- Network installer is advertised but not recommended

cc @hiento09

**Comment by dan-menlo** [comment]
Done
