### ISSUE TITLE
discussion: Simplify Model Structures for Cortex

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1410]
### Goals:
1. Model list should be compact and not overwhelm user with super long model names
2. User's UX - should be easy to call a specific model with an expected alias

### Concepts
- Model Repo: i.e. tinyllama, or bartowski/...
- Model Source: huggingface, cortex
- Model Version: i.e. specific quant, that belongs to a Model Repo
- Model ID: should be <Model Source>:<Version>
- Model Alias: user-defined shortname

## Questions
1. How are we currently generating the model alias for HF models?
3. How do we align with user expectations? to run the model using the same alias they pulled it with?
4. How does this map between `model.yaml` and model table in `cortex.db`, which need to be mapped to Model List

## Resources
Output of `cortex models list` 
![image](https://github.com/user-attachments/assets/a607a2f5-8223-41f7-a660-907ee61364e3)

**Comment by nguyenhoangthuan99** [comment]
Logic for generating short aliases for models in the nightly version:

1. Start with the unique model ID, e.g., 
   `huggingface.co:bartowski:Meta-Llama-3.1-8B-Instruct-GGUF:Meta-Llama-3.1-8B-Instruct-Q2_K`

2. Check if the lowercase version of the last part (`Meta-Llama-3.1-8B-Instruct-Q2_K` -> 
   `meta-llama-3.1-8b-instruct-q2_k`) is unique. If so, use it as the alias. If not, proceed to step 3.

3. Progressively include more parts of the ID from right to left, converting to lowercase, 
   until a unique alias is found or the full original ID is reached.

Rationale for this approach:

1. Many quantization levels are typically stored in the same HuggingFace repository folder 
   (e.g., https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/tree/main, https://huggingface.co/QuantFactory/Mistral-Nemo-Base-2407-GGUF/tree/main). 
   The filename often contains sufficient information about the model architecture and 
   quantization level. When users download from HuggingFace, providing the GGUF filename 
   as the primary alias helps them identify the specific quantization level they're using or testing.
![Image](https://github.com/user-attachments/assets/453188b8-f7aa-4096-8f92-514485bfae9a)
2. Generating a shortened, unique, and human-readable alias from a random string is challenging. 
   Using only part of the ID (e.g., `bartowski:Meta-Llama-3.1-8B-Instruct-GGUF`) as an alias 
   could lead to confusion when users want to pull different quantization levels from the same 
   repository.

3. To improve user experience, we should clearly display both the correct model ID and the 
   model alias after download completion. The current approach needs improvement in this regard.

![Image](https://github.com/user-attachments/assets/5656fe8a-8813-4ab7-9b3d-da0415d6f98c)


This is my personal perspective and doesn't necessarily represent the majority of users. If you have any recommendations for improving the algorithm to enhance user experience, I'm open to updating the logic. I believe changing the default model alias to `bartowski/Meta-Llama-3.1-8B-Instruct-GGUF` may not be ideal. The CLI app is primarily used by developers, who typically require more detailed information about the model they're working with.

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 I see your point. I think we need to broaden the scope of the discussion beyond Model Alias, and deal more broadly with how we handle "Model Naming" in Cortex (i.e. Repo, Version, ID, aliases)

## Model Nomenclature

I think we should clearly define different concepts: 

- Model Repo: i.e. `tinyllama`, or `bartowski/...`
- Model Source: `huggingface`, `cortex`
- Model Version: i.e. specific quant, that belongs to a Model Repo
- Model ID: should be `<Model Source>:<Version>`
- Model Alias: user-defined shortname

We should also be very clear on the behavior for `cortex pull` and `cortex run`. 
- Most users will be used to having the Model Repo as the "name"
- They used that phrase to pull the repo, and would ostensibly take that as the Model ID
- Model Alias is a "shortname" that is user-defined (should not be system defined)

## Model List

- Given the complexity of Huggingface Model IDs and names, I think we need a simpler way to show Model Lists
- I've created a separate issue in #1426 to track this

## Aliases for HF Models?

- We can consider forcing users to "alias" a Huggingface model as they are downloading it
- As you correctly pointed out, Huggingface Model names are very long
- However, I could see this being very complicated for users, UX-wise

cc @gabrielle-ong @0xSage 
cc @vansangpfiev @namchuai

**Comment by dan-menlo** [comment]
Merging in my issue on `model list`, which is really an issue on Model Naming across our repo: 

## Issue

I would like to propose a clearer way to handle model list. I think our current method leads to poor UX, and overcomplicates things:

## Goal

- Model list should be compact and not overwhelm user with super long model names
    - Current status quo is unreadable
- Huggingface listings are very long/complicated
    - I don't think there's an easy path to simplify them
    - We need to brainstorm for ways to simplify
- Model List will be part of other commands, e.g. `cortex run` without any args pulls up numbered list for user to choose from

The big issue with this is the Huggingface Models: 
- We need to figure out `model id` and `model alias` for Huggingface
- The issue is that there is no standard format for Huggingface

From my POV, the "raw" data structure is as follows. We will need to simplify this to human-readable terms:

| Index | model repo                             | model version                               | model source | engine    |
| ----- | ----------------------------------------- | ------------------------------------- | ------------ | --------- |
| 1     | tinyllama                                 | q4_km                                 | cortex       | llama.cpp |
| 2     | tinyllama                                 | q2                                    | cortex       | llama.cpp |
| 3     | bartowski/Meta-Llama-3.1-8B-Instruct-GGUF | meta-llama-3.1-8b-Instruct-IQ2_m.gguf | huggingface  | llama.cpp |
| 4     | bartowski/Meta-Llama-3.1-8B-Instruct-GGUF | meta-llama-3.1-8b-instruct-q4k_m.gguf | huggingface  | llama.cpp |

## Resources

Current Model List looks really bad for Huggingface models

![Image](https://github.com/user-attachments/assets/9dcd8745-7ec9-4ebb-bff8-afd40cf1530c)

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 @gabrielle-ong For Model Naming, can I recommend the following:

- We have `/` in human-readable Model IDs and versions
- This should match the "model source" that users use when `cortex pull` or `cortex run`
- We can convert this to `:` behind the scenes, e.g. for folders etc

## Cortex

This is very straightforward, as we are defining the standards: 

| Field         | Value               | Example         |
| ------------- | ------------------- | --------------- |
| Model Repo    | repo_name           | tinyllama       |
| Model Version | branch_name         | q4k_m<br>       |
| Model Source  | domain              | cortex          |
| Model ID      | UUID<br>repo:branch | tinyllama:q4k_m |
| Model Alias   | user-defined        | string          |

## Huggingface

| Field         | Value               | Example                                                                                      |
| ------------- | ------------------- | -------------------------------------------------------------------------------------------- |
| Model Repo    | repo_name           | bartowski/Meta-Llama-3.1-8B-Instruct-GGUF<br>tinyllama                                       |
| Model Version | quant_filename      | meta-llama-3.1-8b-Instruct-IQ2_m.gguf<br>                                                    |
| Model Source  | domain              | huggingface                                                                                  |
| Model ID      | UUID<br>repo:branch | bartowski/Meta-Llama-3.1-8B-Instruct-GGUF<br>tinyllama:meta-llama-3.1-8b-Instruct-IQ2_m.gguf |
| Model Alias   | user-defined        | string                                                                                       |

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 For Huggingface Models, I think the long-term solution is:

1. User is prompted to pick alias when pulling Huggingface repo
1. `cortex run <huggingface_repo>` shows menu if more than 1 version is downloaded
1. `cortex run` without args shows list of downloaded models, user can pick by number

The core issue to this is that Model ID should ideally != Huggingface Repo name and filename, which is insanely long. I see a user-defined alias as the only long-term solution.

**Comment by dan-menlo** [comment]
- [ ] Remove `id` from `model.yaml`
- [ ] Move from `:` to `/` in `model` (including `aliases`)

**Comment by dan-menlo** [comment]
Mapping between `model.yaml` and `model` table in `cortex.db`, which need to be mapped to Model List

| model table | model.yaml | Description |
|--------|--------|--------|
| `model` | `model` | Unique identifier for the model  |
| `author_repo_id` | Doesn't exist | Author or repository identifier |
| `branch_name` | Doesn't exist | Branch name in the repository |
| `path_to_model_yaml` | Implied | Path to the model's YAML file |
| `model_alias` | User-defined | Shortened alias for the model |

**Comment by dan-menlo** [comment]
After discussion with @nguyenhoangthuan99 @gabrielle-ong, we will KIV this to discuss at Retreat. 

- This is likely to affect the core logic of how we handle models
- e.g. Models table in `cortex.db` and `model.yaml`

From my POV, we should simplify Models List to an extremely simple data structure: 

- Model Alias can be overloaded with multiple versions
- Model ID holds most of the complexity (i.e. engine, quantization, etc)
- We should prompt users to alias Huggingface models, at `pull` or `run`

### Example
```
> cortex models list
```

Result: 
| Index | Alias      | Model ID                                                |
| ----- | ---------- | ------------------------------------------------------- |
| 1     | tinyllama  | tinyllama:1b-gguf                                       |
| 2     | tinyllama  | tinyllama:1b-gguf                                       |
| 3     | mistral           | bartowski/Mistral-8b-instruct-gguf:Mistral-8b-instruct-8b.q4k_m |
| 4     |  mistral          | mistral:7b |
| 5     | gabbyllama | huggingface.co/bartowski/Mistral-8b-instruct-gguf:quant

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 Can you come with a clear Spec for Models Data Structures: 

1. cortex.db Models Table -> what are the fields
2. Model Aliases are non-unique, and if it is overloaded, asks user to choose which model ID they want to run (using integer indexes)
3. Huggingface Models -> user is asked to pick model alias: https://github.com/janhq/cortex.cpp/issues/1410#issuecomment-2392926947

**Comment by nguyenhoangthuan99** [comment]
# cortex.db Models Table Structure and User Experience Improvements

## 1. Models Table Structure

The `Models` table should contain 3 fields:
- Model Alias (can be overloaded with multiple versions)
- Model ID (holds most of the complexity, e.g., engine, quantization, model source, model architecture, etc.)
- Path to model.yml

We should prompt users to alias Hugging Face models during `pull` or `run` operations.

Example table structure:

| Index | Alias      | Model ID                                                |
|-------|------------|----------------------------------------------------------|
| 1     | tinyllama  | tinyllama:1b-gguf                                       |
| 2     | tinyllama  | tinyllama:1b-gguf                                       |
| 3     | mistral    | bartowski/Mistral-8b-instruct-gguf:Mistral-8b-instruct-8b.q4k_m |
| 4     | mistral    | mistral:7b                                              |
| 5     | mistral    | nvidia-cloud/Mistral-Nemo-12b:int4                      |
| 6     | gabbyllama | huggingface.co/bartowski/Mistral-8b-instruct-gguf:quant |

Question: should we show the `path to model.yml` when `cortex models list`?

## 2. Handling Non-unique Model Aliases

When a model alias is overloaded, ask the user to choose which model ID they want to run (using integer indexes):

```
$ cortex run mistral

1. bartowski/Mistral-8b-instruct-gguf:Mistral-8b-instruct-8b.q4k_m
2. mistral:7b 
3. nvidia-cloud/Mistral-Nemo-12b:int4

Please select model to run: 2
mistral:7b Loaded!

>
```

Users can also run directly with the `model ID`:

```
$ cortex run mistral:7b
mistral:7b Loaded!
>
```

## 3. Aliasing Hugging Face Models

We should prompt users to alias Hugging Face models during `pull` or `run` operations, or set it as the default `author/repo_id`.

### Setting a custom alias with the `--alias` flag:

```
$ cortex pull bartowski/Mistral-Nemo-Instruct-2407-GGUF --alias mistral-nemo
Select an option:
    1. Mistral-Nemo-Instruct-2407-IQ2_M.gguf
    2. Mistral-Nemo-Instruct-2407-IQ3_M.gguf
    ...
    10. Mistral-Nemo-Instruct-2407-Q3_K_XL.gguf

Select an option (1-10): 1
Download 'Mistral-Nemo-Instruct-2407-IQ2_M.gguf' finished.

$ cortex models list
| Index | Alias        | Model ID                                                                    |
|-------|--------------|-----------------------------------------------------------------------------|
| 1     | mistral-nemo | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ2_M |
| 2     | bartowski/Mistral-Nemo-Instruct-2407-GGUF | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ3_M |
```

### Setting the default alias as `author/repo_id` when `--alias` is not defined:

```
$ cortex pull bartowski/Mistral-Nemo-Instruct-2407-GGUF
Select an option:
    1. Mistral-Nemo-Instruct-2407-IQ2_M.gguf
    2. Mistral-Nemo-Instruct-2407-IQ3_M.gguf
    ...
    10. Mistral-Nemo-Instruct-2407-Q3_K_XL.gguf

Select an option (1-10): 1

Download 'Mistral-Nemo-Instruct-2407-IQ2_M.gguf' finished.

$ cortex models list
| Index | Alias                                     | Model ID                                                                    |
|-------|-------------------------------------------|-----------------------------------------------------------------------------|
| 1     | bartowski/Mistral-Nemo-Instruct-2407-GGUF | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ2_M |
| 2     | bartowski/Mistral-Nemo-Instruct-2407-GGUF | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ3_M |

$ cortex run bartowski/Mistral-Nemo-Instruct-2407-GGUF

1. bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ2_M
2. bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ3_M

Please select model to run: 2
```

This approach provides a more dynamic user experience and reduces confusion regarding the `--alias` flag.

## Tasks Breakdown

- [ ] Chore: Remove `author_repo_id` and `branch` fields from the `Models` table.
- [ ] Chore: Allow setting of duplicate aliases.
- [ ] Logic update for `cortex pull` and `run` commands:
    - [ ] Implement model selection when multiple versions exist for an alias.
    - [ ] Add option to set custom aliases during `pull` operations.
    - [ ] Use `author/repo_id` as default alias when `--alias` is not specified.
- [ ] update API to get all models with the same alias

Note that with this change, the model start API won't work with `model_alias` like stable release `v1.0.0`, The integration of Jan might be affected
cc @namchuai @vansangpfiev  @gabrielle-ong @dan-homebrew

**Comment by dan-menlo** [comment]
## 0. `cortex models list` != `cortex.db` Models Table

I think the proposal below confuses `model list` simplification with the overall `model table` schema: 
- I think it would be very difficult to infer Engine from model ID, for example
- Unless we are using model.yml to infer engine?

## 1. Models Table Structure

@nguyenhoangthuan99 For Models Table structure: 

- I think we should still have the fields (e.g. `repo_url`, `branch`, `engine`) that were part of the original `MODELS` table
- We just don't need to show them in `cortex models list`
- I think they will be useful, especially when we run `cortex models update` 

Can you look through the existing fields, and make a final proposal for Models table fields. 

> ## . Models Table Structure
> The `Models` table should contain 3 fields:
> 
> * Model Alias (can be overloaded with multiple versions)
> * Model ID (holds most of the complexity, e.g., engine, quantization, model source, model architecture, etc.)
> * Path to model.yml
> 
> We should prompt users to alias Hugging Face models during `pull` or `run` operations.
> 
> Example table structure:
> 
> Index	Alias	Model ID
> 1	tinyllama	tinyllama:1b-gguf
> 2	tinyllama	tinyllama:1b-gguf
> 3	mistral

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 This looks good. Thanks!

> ## 2. Handling Non-unique Model Aliases
> When a model alias is overloaded, ask the user to choose which model ID they want to run (using integer indexes):
> 
> ```
> $ cortex run mistral
> 
> 1. bartowski/Mistral-8b-instruct-gguf:Mistral-8b-instruct-8b.q4k_m
> 2. mistral:7b 
> 3. nvidia-cloud/Mistral-Nemo-12b:int4
> 
> Please select model to run: 2
> mistral:7b Loaded!
> 
> >
> ```
> 
> Users can also run directly with the `model ID`:
> 
> ```
> $ cortex run mistral:7b
> mistral:7b Loaded!
> >
> ```
>

**Comment by dan-menlo** [comment]
@nguyenhoangthuan99 For Huggingface models, I would like to suggest a different approach: 

## 3.1: Prompt user to alias Huggingface Models

- The user is already given an interactive menu to choose which quantization to download
- We can ask the user to give the model a name
- This will be ignored if the user specifies the `--alias` in the command
- If the user does not specify, then model alias is blank

```
$ cortex pull bartowski/Mistral-Nemo-Instruct-2407-GGUF
Select an option:
    1. Mistral-Nemo-Instruct-2407-IQ2_M.gguf
    2. Mistral-Nemo-Instruct-2407-IQ3_M.gguf
    ...
    10. Mistral-Nemo-Instruct-2407-Q3_K_XL.gguf

Select an option (1-10): 1
Specify a Model name: 
Download 'Mistral-Nemo-Instruct-2407-IQ2_M.gguf' finished.

$ cortex models list
| Index | Alias        | Model ID                                                                    |
|-------|--------------|-----------------------------------------------------------------------------|
| 1     | mistral-nemo | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ2_M |
| 2     |              | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ3_M |
```

## 3.2: `cortex run` with no args allows user to run models by picking from list

Given the difficulty in running Huggingface models, I recommend an alternate approach: 
- `cortex run` with no arguments lets user pick from a list of models
- We use the selector menu
- This overcomes the difficulty of remembering the Huggingface repo, branches

```
$ cortex run
Please pick a model to run: 
| Index | Alias        | Model ID                                                                    |
|-------|--------------|-----------------------------------------------------------------------------|
| 1     | mistral-nemo | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ2_M |
| 2     |              | bartowski/Mistral-Nemo-Instruct-2407-GGUF:Mistral-Nemo-Instruct-2407-IQ3_M |

Your selection (1-2): 2
```

**Comment by nguyenhoangthuan99** [comment]
# 1. Models Table Structure
I think it clear now, The `Models` table in cortex.db still remains the same as before
| model table | Description |
|--------|--------|
| `model`  | Unique identifier for the model  |
| `author_repo_id`| Author or repository identifier |
| `branch_name` | Doesn't exist | Branch name in the repository |
| `path_to_model_yaml`  | Path to the model's YAML file |
| `model_alias` | Shortened alias for the model  -> need to change this field from unique to allow null and accept duplication| 

result of `cortex models list` will be simplify as follow:
| Index | Alias      | Model ID                                                |
|-------|------------|----------------------------------------------------------|
| 1     | tinyllama  | tinyllama:1b-gguf                                       |
| 2     | tinyllama  | tinyllama:1b-gguf                                       |
| 3     | mistral    | bartowski/Mistral-8b-instruct-gguf:Mistral-8b-instruct-8b.q4k_m |
| 4     | mistral    | mistral:7b                                              |
| 5     |     | nvidia-cloud/Mistral-Nemo-12b:int4                      |
| 6     | gabbyllama | huggingface.co/bartowski/Mistral-8b-instruct-gguf:quant |

The `engine` will be infer from `model.yml` of each model. We will read the `model.yml` through `path_to_model_yaml`. `Model ID` in  `model list` result command = `model` field in `Models` table of `cortex.db`

for `2. Handling Non-unique Model Aliases` and `3. Hugging Face Models` we will follow above instructions.

## Break down into tasks

- [ ] chore: update `Models` table in cortex.db, update models list command.
- [ ] update `model pull` command to support new alias and huggingface logic
- [ ] update `model run` command to support new alias and huggingface logic
- [ ] add needed API: get list model with `alias`

**Comment by namchuai** [comment]
@dan-homebrew @nguyenhoangthuan99, I have a question: Do we really need aliases? A simple query in `cortex.db` would suffice. I don't anticipate many users wanting to add short names for particular models, so this feature may be unnecessary.

**Comment by nguyenhoangthuan99** [comment]
With this new change, I believe `alias` functions more as a model group than a short name, making it easier for users to manage models. However, without aliases, we could modify the logic when running a model as follows:

```
$ cortex models list
| Index | Model ID                                                           |
|-------|---------------------------------------------------------------------|
| 1     | tinyllama:1b-gguf                                                   |
| 2     | tinyllama:1b-gguf                                                   |
| 3     | bartowski/Mistral-8b-instruct-gguf:Mistral-8b-instruct-8b.q4k_m     |
| 4     | mistral:7b                                                          |
| 5     | nvidia-cloud/Mistral-Nemo-12b:int4                                  |
| 6     | huggingface.co/bartowski/Mistral-8b-instruct-gguf:quant |

$ cortex run mis
Please select an option:
1. mistral-nemo:12b-gguf-q8
2. huggingface.co/bartowski/Mistral-8b-instruct-gguf:quant
3. mistral:7b
4. nvidia-cloud/Mistral-Nemo-12b:int4 
```

When running, we would find the matching ID from the database. The model list could also include an option to filter out models:

```
$ cortex models list mis
| Index | Model ID                                                           |
|-------|---------------------------------------------------------------------|
| 1     | bartowski/Mistral-8b-instruct-gguf:Mistral-8b-instruct-8b.q4k_m     |
| 2     | mistral:7b                                                          |
| 3     | nvidia-cloud/Mistral-Nemo-12b:int4                                  |
| 4     | huggingface.co/bartowski/Mistral-8b-instruct-gguf:quant |
```
We also need to update API to match with this change

**Comment by dan-menlo** [comment]
@namchuai @nguyenhoangthuan99 I think the regex-based approach is stronger than model alias. Good idea and well done. 

- We should then focus our efforts on "cortex run" with regex search

- If only 1 returns, we run the one model

- If there are multiple models matched, we show a menu for the user to choose

- If no arg, we show all models and let user choose via menu.

As part of this approach, we would no longer need model alias field. 

Great idea and this is a lot more elegant. Good suggestion!

**Comment by gabrielle-ong** [comment]
Closing this discussion, thanks @nguyenhoangthuan99, @namchuai!
Creating a new epic at #1512 for implementation
