### ISSUE TITLE
epic: Cortex v1.0.1 QA (22 Oct 2024) [nightly v192]

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1535]
Nightly v192
Release candidate for v1.0.1
-----
## OSes
- [x] Windows 11 (online & offline)
- [ ] Ubuntu 24, 22 (online & offline)
- [x] Mac Silicon OS 14/15 (online & offline)
- [ ] Mac Intel (online & offline)

# 1. Manual QA
## Installation
- [x]  it should install with network installer
- [x]  it should install with local installer
- [x] it should install 2 binaries (cortex and cortex-server)
- [x]  it should install with correct folder permissions
- [x]  it should install with folders: /engines /logs (no /models folder until model pull)

## Data/Folder structures
- [x] cortex.so models are stored in `cortex.so/model_name/variants/`, with .gguf and model.yml file
- [x] huggingface models are stored `huggingface.co/author/model_name` with .gguf and model.yml file
- [x] downloaded models are saved in cortex.db (view via SQL)
- [ ] [to add] tests for copying models data folder & relative paths

## Cortex Update
- [x] cortex -v should check output current version and check for updates
- [x] cortex update replaces the app, installer, uninstaller and binary file (without installing cortex.llamacpp)
- [x]  cortex update should update from ~3-5 versions ago to latest (+3 to 5 bump)
- [x]  cortex update should update from the previous version to latest (+1 bump)
- [ ] cortex update should update from previous stable version to latest (stable checking)
- [x]  it should gracefully update when server is actively running

## Overall / App Shell
- [x] cortex returns helpful text in a timely* way
- [x] `cortex` or `cortex -h` displays help commands
- [x] CLI commands should start the API server, if not running [WIP `cortex pull`, `cortex engines install`]
- [x] it should correctly log to cortex-cli.log and cortex.log
- [x] There should be no stdout from inactive shell session

## Engines
- [x] llama.cpp should be installed by default
- [x]  it should run gguf models on llamacpp
- [x] it should install engines
- [x] it should list engines (Compatible, Ready, Not yet installed)
- [x] it should get engines
- [x] it should uninstall engines
- [x]  it should gracefully continue engine installation if interrupted halfway (partial download)
- [x]  it should gracefully handle when users try to CRUD incompatible engines (No variant found for xxx)
- [ ]  it should run trtllm models on trt-llm [WIP,  not tested]
- [ ] it shoud handle engine variants [WIP, not tested]
- [ ]  it should update engines versions [WIP, not tested]

## Server
- [x] `cortex start` should start server and output API documentation page
- [x] users can see API documentation page 
- [x]  `cortex stop` should stop server
- [x]  it should correctly log to cortex logs
- [x]  `cortex ps` should return server status and running models (or no model loaded)

## Model Pulling
- [x] Pulling a model should pull .gguf and model.yml file
- [x] Model download progress should appear (with accurate %, total time, download size, speed)
### cortex.so
- [x]  it should pull by built in model_ID
- [x] pull by model_ID should recommend default variant at the top (set in HF model.yml)
- [x]  it should pull by built-in model_id:variant
### huggingface.co
- [x]  it should pull by HF repo/model ID
- [x]  it should pull by full HF url (ending in .gguf)
### Interrupted Download
- [x] it should allow user to interrupt / stop download 
- [x] pulling again after interruption should accurately calculates remainder of model file size neeed to be downloaded (`Found unfinished download! Additional XGB needs to be downloaded`)
- [x]  it should allow to continue downloading the remainder after interruption

## Model Management
- [x]  it should list downloaded models
- [x] it should get info of a local model
- [x]  it should update models
- [x] it should delete a model
- [x]  it should import models with model_id and model_path
- [ ] [To deprecate] it should alias models (deprecate once `cortex run` with regex is implemented)

## Model Running
- [x] `cortex run <cortexso model>` - if no local models detected, shows `pull` model menu
- [x] `cortex run` - if local model detected, runs the local model
- [x]  `cortex run` - if multiple local models detected, shows list of local models for users to select
- [x] `cortex run <invalid model id>` should return gracefully `Model not found!`
- [x]  run should autostart server
- [x] `cortex run <model>` starts interactive chat (by default)
- [x] `cortex run <model> -d` runs in detached mode
- [x] `cortex models start <model>`  
- [x] terminate StdIn or `exit()` should exit interactive chat

## Hardware Detection / Acceleration [WIP]
- [ ]  it should auto offload max ngl
- [ ]  it should correctly detect available GPUs
- [ ]  it should gracefully detect missing dependencies/drivers
CPU Extension (e.g. AVX-2, noAVX, AVX-512)
GPU Acceleration (e.g. CUDA11, CUDA12, Vulkan, sycl, etc)

## Uninstallation / Reinstallation
- [x]  it should uninstall 2 binaries (cortex and cortex-server)
- [x]  it should uninstall with 2 options to delete or not delete data folder 
- [x]  it should gracefully uninstall when server is still running
- [x] uninstalling should not leave any dangling files
- [x] uninstalling should not leave any dangling processes
- [x]  it should reinstall without having conflict issues with existing cortex data folders

--
# 2. API QA

## Overall API
- [x] API page is updated at localhost:port endpoint (upon `cortex start`)
- [ ] OpenAI compatibility for below
- [ ] https://cortex.so/api-reference is updated

### Chat Completions
- [x] POST `v1/chat/completions`

### Engines
- [x] GET `/v1/engines`
- [x] DELETE `/v1/engines/install/{name}`
- [x] POST `/v1/engines/install/{name}`
- [x] GET `/v1/engines/{name}`

### Models
- [x] GET `/v1/models` lists models
- [x] POST `/v1/models/pull` starts download (websockets)
- [x] `websockets /events` emitted when model pull starts 
- [x] DELETE `/v1/models/pull` stops download (websockets)
- [x] `websockets /events` stopped when model pull stops
- [x] POST `/v1/models/start` starts model
- [x] POST `/v1/models/stop` stops model
- [x] DELETE `/v1/models/{id}` deletes model
- [x] GET `/v1/models/{id}` gets model
- [x] PATCH `/v1/models/{model}` updates model.yaml params

--------
Test list for reference:
- #1357 e2e tests for APIs in CI
- #1147, #1225 for starting QA list
