### ISSUE TITLE
roadmap: Cortex API supports `/threads`, `/messages`

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1567]
## Goal 

- Cortex takes over management of Threads, Messages from Jan
    - Cortex API supports `/threads`, `/messages`
- Cortex should take over data structures for Threads, Messages
    - e.g. `/threads` folder in data folder
    - We should not make any changes to this
- Linked: https://github.com/janhq/jan/issues/3904

## Questions

- Should we have `cortex.db` keep track of all Threads (vs. `fs` lookups = inefficient)
- Should we move Threads into `cortex.db`?
    - Dan's view: I don't think so, `messages.jsonl` and `thread.json` are useful primitives, and we should avoid bloating SQLite

**Comment by louis-jan** [comment]
## Problems
`/messages` is quite straightforward for now but Jan's `/threads` is a combination of `model preset, assistant parameters, assistant tools and threads`.
Also `/assistants` is not well designed, it defaults to a hard-coded template.

See a Jan `thread.json` example:
```json
{
  "id": "jan_1729768043",
  "object": "thread",
  "title": "0.5.8 llama 3.2 1b",
  "assistants": [
    {
      "assistant_id": "jan",
      "assistant_name": "Jan",
      "tools": [
        {
          "type": "retrieval",
          "enabled": true,
          "settings": {
            "top_k": 2,
            "chunk_size": 1024,
            "chunk_overlap": 64,
            "retrieval_template": "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n----------------\nCONTEXT: {CONTEXT}\n----------------\nQUESTION: {QUESTION}\n----------------\nHelpful Answer:"
          }
        }
      ],
      "model": {
        "id": "llama3.2-1b-instruct",
        "settings": {
          "engine": "llama-cpp",
          "ctx_len": 3072,
          "ngl": 100,
          "prompt_template": "<|start_header_id|>system<|end_header_id|>\n\n{system_message}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n",
          "text_model": false
        },
        "parameters": {
          "engine": "llama-cpp",
          "frequency_penalty": 0,
          "max_tokens": 3072,
          "presence_penalty": 0,
          "stop": [
            "<|eot_id|>"
          ],
          "stream": true,
          "temperature": 0.699999988079071,
          "top_p": 0.949999988079071
        },
        "engine": "llama-cpp"
      },
      "instructions": ""
    }
  ],
  "created": 1729768043312,
  "updated": 1730195853233,
  "metadata": {
    "lastMessage": "Hello!"
  }
}
```

See OpenAI Assistant and Thread:
```json
{
  "id": "asst_abc123",
  "object": "assistant",
  "created_at": 1698984975,
  "name": "Math Tutor",
  "description": null,
  "model": "gpt-4o",
  "instructions": "You are a personal math tutor. When asked a question, write and run Python code to answer the question.",
  "tools": [
    {
      "type": "code_interpreter"
    }
  ],
  "metadata": {},
  "top_p": 1.0,
  "temperature": 1.0,
  "response_format": "auto"
}
```

```json
{
  "id": "thread_abc123",
  "object": "thread",
  "created_at": 1699012949,
  "metadata": {},
  "tool_resources": {}
}
```

## So should we:
1. Introduce a new structure similar to an existing one and scoped by `/threads` and `/messages`
2. Follow a popular schema such as OpenAI that could scale to `/assistants`

I think 2 is preferred since we could take advantage of existing test suites and client SDKs. Otherwise, we would eventually do another migration to scale to `/assistants` and double the workload, such as writing tests.

## Decouple `threads` & `/models`
Currently, they are coupled and fairly similar to preset, which is not really well-defined. E.g. thread.json defines model settings, which created a side effect where switching between threads would also reload the model. It's an antipattern, and we should find a way to decouple it.

1. Inference parameters & tools go to `/assistants`. It's to scale `/assistants` better where users can have more than one assistant persona (instructions + parameters) instead of hard coding.
2. Model parameters go to `/models` where PUT takes effect (now it's used nowhere)
3. The thread is now fairly thin. Better to scale to `/runs` as well, it is a likely a container that glue components together (assistant, run, file_stores)

## Keep incomplete things thin.
As described above,`/threads` work strictly with `assistants` and `runs` and both of those are not ready yet. Build out `/threads` to a structured db would kill us while completing the API set. We will have to migrate many times before all of those are well battle-tested. So I would prefer an unstructured database system, so migrating would not be a nightmare for the time being.

**Comment by dan-menlo** [comment]
@louis-jan I agree that Option 2 is correct - i.e. we follow the OpenAI Schema an Threads, Messages, Assistants and Models. I would like to start to find an incremental approach to get there to reduce major change risk. 

Can I check my understanding of your proposal: 

## Ideal Outcome

- Cortex will have a cleaner schema which is aligned with OpenAI's schema
    - `/assistants` -> Cortex DB "Assistants" table -> `assistant.yaml`
    - `/threads` -> Cortex DB "Theads" table -> `thread.json`
    - `/models` -> Cortex DB "Models" table -> `model.yaml`

## Key Questions

### Can Users customize a single Thread's inference params?
- I agree that per-thread Model and Assistant settings introduces too much complexity
    - I think we can give them the option to edit it when Thread is in focus, and save it as Model or Assistant settings
    - Otherwise, any changes made will be lost once the user navigates out of the Thread
- We can loop back later on to provide Per-Thread customization 
    - e.g. create a `model.yaml`, `assistant.yaml` in Thread folder
    
### Will we move Threads to a structured DB?
- Imho, we should just have a very simple Threads table in `cortex.db`
    - This should just be a lookup table for the individual Threads folders
- We should continue to have Threads folders which hold `messages.jsonl` and `thread.json`
- We should start to version `thread.json`, as it is likely that we will have multiple versions

### How will we deal with legacy Threads?
- Should we just focus on fresh conversations, and let legacy Conversations extension deal with older Threads in Jan?
- Or: should we write a migration script? (would we discard Per-Thread model customizations?)

**Comment by louis-jan** [comment]
Hi @dan-homebrew 
1. I definitely agreed with the approach.
2. That is a great idea, a lookup table would really help to boost the performance.
3. I think we would want to deal with it slowly. After Jan moves the model settings to `/models`, that would be easier to migrate `/threads`. Or even easier to just glue legacy and new data together with a simple transform function for the time being.

**Comment by louis-jan** [comment]
@dan-homebrew @janhq/cortex This is the visualization diagram of how we are going to structure and support. Green components are in scope, red components are out of scope.

![Screenshot 2024-10-30 at 13 07 37](https://github.com/user-attachments/assets/e58129fe-9c32-4330-8207-463dc69d9199)

**Comment by dan-menlo** [comment]
Can I clarify my understanding: 

- `Watcher` monitors files for changes? (does it reload?)
- `Runner`: what does this do?

> ![Screenshot 2024-10-30 at 13 07 37](https://private-user-images.githubusercontent.com/133622055/381413708-e58129fe-9c32-4330-8207-463dc69d9199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzE1MDgsIm5iZiI6MTczMDI3MTIwOCwicGF0aCI6Ii8xMzM2MjIwNTUvMzgxNDEzNzA4LWU1ODEyOWZlLTljMzItNDMzMC04MjA3LTQ2M2RjNjlkOTE5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNjUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTExN2E3ZGI3NWQyMjViZTg2MjZjOTE0MzUyMWE1MTM0MTVhNDQ0YTZmNTcwMjFhNzczOTA2MTIzYjNkZTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2E5h3DuntcyOceN6m2mtbJ_1Qsq-kTOtEoxU55RqZ9s)

**Comment by dan-menlo** [comment]
I super agree with the strategy to just glue legacy and new data with a simple transform function: 

1. We figure out what the new data structure should be and implement it in Cortex.cpp
    - Make sure new data structures include `v1` in the JSON or YAML, so that we can make rapid upgrades
2. We transform old data structures into new data structures at runtime
3. We eventually write a migration script, once the data structures have settled (somewhat)

> 3. I think we would want to deal with it slowly. After Jan moves the model settings to `/models`, that would be easier to migrate `/threads`. Or even easier to just glue legacy and new data together with a simple transform function for the time being.

**Comment by louis-jan** [comment]
> Can I clarify my understanding:
> 
> * `Watcher` monitors files for changes? (does it reload?)
> * `Runner`: what does this do?
> 
> > ![Screenshot 2024-10-30 at 13 07 37](https://private-user-images.githubusercontent.com/133622055/381413708-e58129fe-9c32-4330-8207-463dc69d9199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzE1MDgsIm5iZiI6MTczMDI3MTIwOCwicGF0aCI6Ii8xMzM2MjIwNTUvMzgxNDEzNzA4LWU1ODEyOWZlLTljMzItNDMzMC04MjA3LTQ2M2RjNjlkOTE5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNjUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTExN2E3ZGI3NWQyMjViZTg2MjZjOTE0MzUyMWE1MTM0MTVhNDQ0YTZmNTcwMjFhNzczOTA2MTIzYjNkZTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2E5h3DuntcyOceN6m2mtbJ_1Qsq-kTOtEoxU55RqZ9s)

Yeah, just to monitor file changes, it's good to have, minor one. I dont know how to name engine running stuff that is not related to the business layer, so just leave it runner 😆.

**Comment by dan-menlo** [comment]
@namchuai @louis-jan For Threads/Models/Assistants, I recommend we take an incremental approach: 

## V1 Threads

- We should add a version to all current Thread.json as having `version: 1`
- We should have a v1 thread handler in Cortex, that recognizes and can parse Model, Assistant from v1 Thread
- We should still cover this with test coverage

## V2 Threads

- We should design the ideal structure for V2 Threads (eg Model, Thread, Assistant)
- I still think that user should be able to have per-thread model params - this can be achieved by creating a model.yaml in the Thread folder 
- This enables us to have clear separation of concerns between Thread, Model and Assistant

**Comment by TC117** [comment]
@namchuai @sangjanai can you help add the `/threads` and `/messages` to doc page? `http://127.0.0.1:39281/#tag/threads`
please cmiiw, for V1, we only query for Jan folder so only 
we will try to replace these endpoints 
![image](https://github.com/user-attachments/assets/386bf289-3f2d-458b-9f55-7bdfc589ad5f)

**Comment by TC117** [comment]
thread
- [x] GET : List of threads
Empty list
![image](https://github.com/user-attachments/assets/476e675f-d202-4a24-9c54-71eaad8b7066)
Array of thread
![image](https://github.com/user-attachments/assets/7acc61e7-341e-4733-a922-41dea0bccb42)

- [x] GET retrieve thread
![image](https://github.com/user-attachments/assets/a131ca5f-7e98-45b9-9fe7-ae2414d42f0a)
![image](https://github.com/user-attachments/assets/2f8d9b1c-7810-4258-b596-31e30132c1c7)
 
- [x] Post new thread
![image](https://github.com/user-attachments/assets/ce71d326-e8dd-41d9-a4e0-bdcee1d614da)
![image](https://github.com/user-attachments/assets/8e6eb8ce-7587-4dca-a739-8e75ecb581d3)

- [x] Delete a thread
![image](https://github.com/user-attachments/assets/2951dd0f-a962-47a9-bb2c-28849defd536)
![image](https://github.com/user-attachments/assets/f3ca2136-c39a-4cc3-86a7-125247516ed8)

Message
- [x] GET List of message of a thread
![image](https://github.com/user-attachments/assets/f936bbc5-bc0e-4d08-b1c5-85605acf4102)
![image](https://github.com/user-attachments/assets/66adb11a-1f36-4f8a-ab82-3895aab68c12)

- [x] Post Message 

- [x] GET Message with ID
![image](https://github.com/user-attachments/assets/52b8e537-4e7b-4d3c-ab31-48ea080f7568)

**Comment by TC117** [comment]
@namchuai 
❌ Cant patch the thread title
![image](https://github.com/user-attachments/assets/70794897-f358-4c51-9cc8-5dff29d644a9)

**Comment by namchuai** [comment]
@TC117 , thread title will be stored in metadata. Since OpenAi's [Thread object](https://platform.openai.com/docs/api-reference/threads/object) does not have title.

So, in order to update the title, please use this for example:
```
curl --location 'http://127.0.0.1:39281/v1/threads/0001KN04SY7D75K0MPTXMXCH39' \
--header 'Content-Type: application/json' \
--data '{
    "metadata": {
        "title": "my title"
    }
}'
```

**Comment by TC117** [comment]
Thanks @namchuai, Got it so we not use PATCH for modify 👍

**Comment by louis-jan** [comment]
Updated to use PATCH. Completed.
