### ISSUE TITLE
epic:  Implement Cortex Hardware API for Nvidia

### ISSUE THREAD

**Issue by vansangpfiev** [janhq/cortex.cpp#1568]
Implementation for https://github.com/janhq/cortex.cpp/issues/1165

- Scope to Nvidia first (AMD, Intel, Qualcomm to subsequent sprints)

## Tasklist
(Will fill in details when implement each task)

### Hardware API
- [x] Hardware Detection
    - [x] Implement platform-specific detection
    - [x] Implement GPU-specific detection
    - [x] #1591
    - [x] Develop separate modules for Windows, Linux, and macOS to gather hardware information
    - Use appropriate system calls and libraries
- [x] Implement CLI for hardware activation
- [x] Implement RAM check for CPU fallback
- [x] #1603
- [x] Documentation

### `/engines`
- [x] Modify engine initialization
- [x] Implement hardware passing to engines

### `/model/start`
- [ ] Handle `ngl` settings (in `/models/start`)
- [ ] Implement RAM and VRAM detection
- [x] Implement fallback logic

### Jan

- [ ] System Monitor
- [ ] Model Start
- [ ] Engines Settings?

## Bugs to Address

- [ ] #1459 

## Related bugs:
- #1468
- #1458
- #1104
- #1525 

## Out-of-scope

- AMD
- Intel
- Qualcomm/Snapdragon

**Comment by vansangpfiev** [comment]
# Hardware API Documentation

## Get hardware information
```http
GET /v1/hardware
```
**Response:**
```json
{
  "cpu": {
    "arch": "string",
    "cores": number,
    "model": "string",
    "instructions": ["string"]
  },
  "os": {
    "version": "string",
    "name": "string"
  },
  "ram": {
    "total": number,
    "available": number,
    "type": "string"
  },
  "storage": {
    "total": number,
    "available": number,
    "type": "string"
  },
  "gpus": [
    {
      "model": "string",
      "vram": "string",
      "driver_version": "string"
    }
  ],
  "power": {
    "battery_life": number,
    "charging_status": "string",
    "is_power_saving": boolean
  },
  "monitors": [
    {
      "resolution": "string",
      "refresh_rate": number,
      "resolution":"string"
    }
  ]
}
```
## Hardware Activation
```http
POST /v1/hardware/activate
```
```
{
"gpus": [0, 1]
}
```

**Comment by dan-menlo** [comment]
Thanks @vansangpfiev. Will we be implementing deactivate this sprint?

**Comment by vansangpfiev** [comment]
> Thanks @vansangpfiev. Will we be implementing deactivate this sprint?

Since we have `/activate` endpoint, I think it is redundant to add `/deactivate`.
By default, we activate all the GPUs. We deactivate all GPUs that are not in request for `/activate`.

**Comment by dan-menlo** [comment]
A few notes from our quick call: 

## Hardware Support

We will need to work with multiple hardware providers, but these can be dealt with in separate sprints:

- For Intel, can we detect iGPUs, NPUs and CPUs? (i.e. Lunar Lake)
- For AMD, can we detect iGPUs
- For Qualcomm/ARM, can we detect Adreno etc

## `ngl` settings

- We detect hardware to recommend `ngl` setting to users 
- `/models/start` API will infer hardware info from database, and then recommend `ngl`
- This is not part of Hardware API, but `/models/start` is using hwinfo

**Comment by vansangpfiev** [comment]
# CLI Documentation:
## Get hardware information
```
cortex hardware list --cpu --os --ram --storage --gpu --power --monitors
```
If no flag is specified, display all hardware information

## Activate hardware
```
cortex hardware activate --gpus [gpu_list]
```
`gpu_list` is required, `[]` means deactivate all GPUs

## Start model
```
cortex start [model_id] --gpus [gpu_list]
```
`--gpus` is optional, if not specified use all activated GPUs
## Run
```
cortex run [model_id] --gpus [gpu_list]
```
`--gpus` is optional, if not specified use all activated GPUs

**Comment by gabrielle-ong** [comment]
Nicely done @vansangpfiev! Testing it out now - 2 quick questions:
1. I cant seem to deactivate the GPU to test without GPU - 
```
cortex-nightly hardware activate --gpus []
Invalid GPU index provided.
```
2. GPU information has Index=1, ID=0 for the same GPU, which is confusing - can we standardize to using Index like the other fields? 
![image](https://github.com/user-attachments/assets/df5ba8f5-77d3-49f2-ae35-0aff61dd5d43)

**Comment by vansangpfiev** [comment]
> Nicely done @vansangpfiev! Testing it out now - 2 quick questions:
> 
> 1. I cant seem to deactivate the GPU to test without GPU -
> 
> ```
> cortex-nightly hardware activate --gpus []
> Invalid GPU index provided.
> ```
> 
> 2. GPU information has Index=1, ID=0 for the same GPU, which is confusing - can we standardize to using Index like the other fields?
>    ![image](https://private-user-images.githubusercontent.com/17236572/386063907-df5ba8f5-77d3-49f2-ae35-0aff61dd5d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjQ2MTAsIm5iZiI6MTczMTU2NDMxMCwicGF0aCI6Ii8xNzIzNjU3Mi8zODYwNjM5MDctZGY1YmE4ZjUtNzdkMy00OWYyLWFlMzUtMGFmZjYxZGQ1ZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA2MDUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYmEwOTZkM2UzMTJiOWFkNzY0ZmMwZTc4ZDlmODE2OTk5YWJkMTkwODk1YWUxYWNhYzVjMTQ2NGRhOWE0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dsdKuC7D0Tbzs3GAimfqOXKCql-cAZjF8zHX7Z1Lnso)

Thanks @gabrielle-ong 
1. Let me take a look. Would you mind sharing the cortex.log and cortex-cli.log?
2. Sure, let me fix it. Actually, the `ID` is the GPU ID that `nvidia-smi` reports, it can be different from `#index`.

**Comment by gabrielle-ong** [comment]
Thanks Sang!
2 - I see, understand. then it'll help to make it clear its the nvidia-smi ID through the help command

1- it just takes in the empty array, no error logs.
cortex-cli.log
```
20241114 06:32:23.404000 UTC 13784 INFO  CUDA Version: 12.4 - utils/system_info_utils.h:141
20241114 06:32:23.404000 UTC 18228 INFO  Will check for new update, time from last check: 2531 seconds - cortex_upd_cmd.cc:127
20241114 06:32:23.404000 UTC 18228 INFO  Engine release path: https://delta.jan.ai/cortex/latest/version.json - cortex_upd_cmd.cc:138
20241114 06:32:23.545000 UTC 18228 INFO  Got the latest release, update to the config file: v1.0.2-235 - cortex_upd_cmd.cc:175
```
cortex.log:
```
20241114 05:38:18.970000 UTC 3728 INFO  Origin:  - main.cc:160
20241114 05:38:19.139000 UTC 12684 INFO  Gpu Driver Version: 551.76 - utils/system_info_utils.h:116
20241114 05:38:19.279000 UTC 12684 INFO  CUDA Version: 12.4 - utils/system_info_utils.h:141
20241114 05:38:19.484000 UTC 12684 INFO  CUDA Version: 12.4 - utils/system_info_utils.h:141
20241114 05:38:19.531000 UTC 12684 INFO  Origin:  - main.cc:160
20241114 05:49:51.989000 UTC 7484 INFO  Origin:  - main.cc:160
20241114 05:49:51.989000 UTC 16792 INFO  activate: {
	"gpus" : 
	[
		0
	]
}
 - hardware.cc:38
20241114 05:49:51.989000 UTC 16792 INFO  No hardware activation changes -> No need to update - hardware_service.cc:211
20241114 05:49:51.989000 UTC 16792 INFO  Origin:  - main.cc:160
20241114 05:50:00.401000 UTC 1384 INFO  Origin:  - main.cc:160
20241114 05:50:00.542000 UTC 4276 INFO  Gpu Driver Version: 551.76 - utils/system_info_utils.h:116
20241114 05:50:00.682000 UTC 4276 INFO  CUDA Version: 12.4 - utils/system_info_utils.h:141
20241114 05:50:00.870000 UTC 4276 INFO  CUDA Version: 12.4 - utils/system_info_utils.h:141
20241114 05:50:00.964000 UTC 4276 INFO  Origin:  - main.cc:160
20241114 05:50:12.567000 UTC 17776 INFO  Origin:  - main.cc:160
20241114 05:50:12.567000 UTC 16092 INFO  activate: {
	"gpus" : 
	[
		1
	]
}
 - hardware.cc:38
20241114 05:50:12.567000 UTC 16092 INFO  Origin:  - main.cc:160
20241114 05:50:37.058000 UTC 15972 INFO  Origin:  - main.cc:160
20241114 05:50:37.058000 UTC 11104 INFO  activate: {
	"gpus" : []
}
 - hardware.cc:38
20241114 05:50:37.058000 UTC 11104 INFO  Origin:  - main.cc:160
20241114 06:32:23.404000 UTC 11156 INFO  Origin:  - main.cc:160
20241114 06:32:23.404000 UTC 6656 INFO  activate: {
	"gpus" : []
}
 - hardware.cc:38
20241114 06:32:23.404000 UTC 6656 INFO  Origin:  - main.cc:160

```

**Comment by vansangpfiev** [comment]
@gabrielle-ong Can you please try again with nightly `236`?

**Comment by gabrielle-ong** [comment]
Thanks Sang! Successfully activate and deactivated GPUs with CLI and API, marking as complete

### Using GPU
![Image](https://github.com/user-attachments/assets/a8bde282-7b19-42d3-80da-72ae5882487c)

### Using CPU
![Image](https://github.com/user-attachments/assets/eae7a31e-690c-4735-bfba-5acfbeb6c94d)
