### ISSUE TITLE
roadmap: Implement Remote engine

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1662]
**Problem**

This epic is implementation of [Remote engine](https://github.com/janhq/cortex-internal/issues/15)

**Success Criteria**
- Cortex supports remote engine for using remote provider (openai, anthropic, ...)
- Cortex supports engine managements for remote engine
- Cortex supports model managements for remote model (gpt-4o, claude, ...)
- Cortex supports API for Chat Completions, Get models and route request to correct remote provider

**Tasklist**
- [x] Implement jinja2 parser and chat completion requests route 
- [x] Implement Get models request route
- [x] Implement Request Transform
- [x] Implement Response Transform
- [x] Implement Engine management
     - [x] Engine table in cortex.db
     - [x] Upsert Remote engine (name & variant would be unique as composite key)
     - [x] Get Remote engine by Id
     - [x] Get Remote engine by name and variant (optional)
     - [x] Delete Remote engine
     - [x] Update API `/v1/engines` to support remote engine
- [x] Implement model management (cortex.cpp)
     - [x] Add remote model.yml
     - [x] Update Remote model.yml
     - [x] List, Get remote models
     - [x] load, unload model
     - [x] chat completion with non stream request
     - [x] chat completion with stream request
     - [x] Integrate with new engine implementation
- [x] Try using transform template with Claude model
- [ ] Support CLI for remote engines
- [x] Docs

**Comment by TC117** [comment]
- [x] Can add remote engine 
![Image](https://github.com/user-attachments/assets/e64d41eb-a8c8-49a5-984a-1cf39308692e)

- [x] Get list of remote engines
![Image](https://github.com/user-attachments/assets/4f8bf399-69a8-4052-ac39-46ef9c2468a2)
