### ISSUE TITLE
Cortex Braindump (Sprint 25)

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/cortex.cpp#1726]
# What has been done (Sprint 25)
### 1.0.3 Release (end of week 1)
- https://github.com/janhq/cortex.cpp/milestone/24?closed=1
- **Key Cortex features:** Engines management, Hardware detection and activation, Docker images, Linux installation (script, binaries), Function Calling, UX improvements 
- **Cortex.llamacpp features:** parameters for /models/start, /chat/completions
- **Bug fixes for Jan 0.5.9:** CORS, HTTPS

# What is ongoing (Sprint 25)
**Cortex Kanban**: https://github.com/orgs/janhq/projects/5/views/38
### 1.0.4 scope (Target: 2 Dec Mon) 
- **Bug fixes for Jan 0.5.10:** 
    - https://github.com/janhq/cortex.cpp/issues/1722
    - https://github.com/janhq/cortex.cpp/issues/1724
    - https://github.com/janhq/cortex.cpp/issues/1684
    - https://github.com/janhq/cortex.cpp/issues/1683
- **New features:** Remote Engines, /messages, Cortex Updater migrations
- Probably moving to **Sprint 26**: Vision models, k8 deployment, model/sources, align cortex.llamacpp with llamacpp version
- **Qn:** inactive user bugs "investigating status" - close after 1 month?
-----
# Mental Model
## 1. Product
**PM**
- Daily: Review Eng tickets / PRs code and progress
- Feature level: Write specs / acceptance criteria
    - currently speced during QA => to move to before implementation with engineers
- Roadmap: Curate New features
    - currently created tickets, unprioritised / untracked

**QA**
- Daily: QA by Feature level (tickets in QA)
- QA nightly cortex for regression

**Docs, Tutorials, blogs**
- Help with docs for new features
- [NEED DIRECTION] how to rewrite delightful docs
- Blog idea: Cortex with Open Web UI (people want web? common qn)
- Blog idea: Build something with Cortex (copy a open AI tutorial)
- Tutorial idea: Build with Cortex and agents framework (eg SwarmZero) to capture mindshare while Agents is the rage https://blog.dailydoseofds.com/p/build-a-multi-agent-research-assistant
- Idea: Work with Abid KDnuggets author who wrote a post on Cortex and many posts on Jan

## 2. People
**Users**
- Daily: Triage user questions in Discord, Github, Reddit, socials
- Feature updates: when fixes/features are out
- User interviews (discord, comments)

**Strategic Partnerships** 
- [ASK FOR HELP] Strategic partnership with Intel, Qualcomm, AMD

## 3. Process - Need to think / automate
**Roadmap / Sprint Planning** 
=> Current view by Kanban, by sprint: https://github.com/orgs/janhq/projects/5/views/38

**QA, Release Management**
- https://github.com/orgs/janhq/projects/5/views/25?filterQuery=Release&pane=issue&itemId=88461134&issue=janhq%7Cqa%7C3
- [ ] Write acceptance criteria during planning/implementation
- [ ] Deprecate nightly, to QA on feature build
- [ ] QN: @dan-homebrew can we Add Tin to Github org, else he cannot be tagged as  assignee (though can be commented)
- [ ] Automate QA

**Comment by gabrielle-ong** [comment]
Closing together with #1735
