### ISSUE TITLE
Replace `cortex.llamacpp` with minimalist fork of `llama.cpp`

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1728]
## Goal 

- Goal: Can we have a minimalist fork of llama.cpp as `llamacpp-engine`
    - cortex.cpp's desktop focus means Drogon's features are unused
    - We should contribute our vision and multimodal work upstream as a form of llama.cpp server
    - Very clear Engines abstraction (i.e. support OpenVino etc in the future)
- Goal: Contribute upwards to llama.cpp
    - Vision, multimodal
    - May not be possible if the vision, audio encoders are Python-runtime based

Can we consider refactoring llamacpp-engine to use the server implementation, and maintain a fork with our improvements to speech, vision etc? This is especially if we do a C++ implementation of whisperVQ in the future.

## Potential issues 
- [ ] `cortex engines llama.cpp update` -> updates llama.cpp
    - We still need to build `avx-512` variants for `janhq/llama.cpp` (i.e. build scripts)
    - We should align the `janhq/llama.cpp` release names with `ggml-org/llama.cpp`
    - Trigger automatic CI/CD to build
    - We can also ask GG if we can donate compute towards builds
- [ ] Deprecating llava support
- [ ] Handling existing API endpoints for `logit_bias`, `n` etc by either upstreaming or in Cortex Server
- [ ] Update Documentation
- [ ] DevRel @ramonpzg 
    - [ ] Cortex builds on llamacpp-server (and we will contribute in the future)
    - [ ] Why do we need to build so many different types of llama.cpp (AVX512, AVX2)
    - [ ] GG -> can we contribute Menlo Cloud to llama.cpp project (built up Intel CPUs)

## Key Changes

- Use `llama-server` instead of Drogon that we use in `cortex.llamacpp`
- Use a spawned `llama.cpp` process instead of `dylib` (better stablity, parallelism)
    - However, we will effectively need to build a process manager

**Comment by vansangpfiev** [comment]
I agree that we should align with the llama.cpp upstream, but I have several concerns:
- `Drogon` is part of `cortex.cpp`, we have already removed it from llama-cpp engine. If we remove `Drogon` from cortex.cpp, we need to find a replacement, which will be costly.
- Repository Structure: Forking the server implementation will necessitate changes to our repository structure, since we currently use llama.cpp as a submodule.
- Our current version differs significantly from the upstream version, which will require considerable time for refactoring.

**Comment by dan-homebrew** [comment]
Close in favor of https://github.com/janhq/jan-internal/issues/11

**Comment by vansangpfiev** [comment]
Tasklist:
- [x] Fork llama.cpp and try to use llama.cpp server
- [x] Split vision model flow with chat model flow 
- [x] llama.cpp server should be a new process
- [x] Test with OpenAI API compatible features that Alex and James added
- [x] CI
- [ ] Docs

Related tickets need to be tested and verified:
- [x] https://github.com/janhq/jan/issues/3785
- [x] https://github.com/janhq/cortex.llamacpp/issues/262
- [x] https://github.com/janhq/cortex.cpp/issues/1102
- [x] https://github.com/janhq/cortex.llamacpp/issues/264
- [x] https://github.com/janhq/cortex.llamacpp/issues/263
- [x] https://github.com/janhq/cortex.cpp/issues/1758
- [x] https://github.com/janhq/cortex.llamacpp/issues/265

Approach 1: `cortex.llamacpp` spawns llama.cpp server as a new process 
- pros: can directly use llama.cpp server binary
- cons: spawn a new process is expensive and hard to control the process lifetime

![image](https://github.com/user-attachments/assets/07519480-c438-47e0-a8a7-a64176178a92)


Approach 2: Build llama.cpp server as a library and load it into `cortex.llamacpp` process
- pros: llama.cpp server can be embedded into `cortex.llamacpp`
- cons: will need to apply a patch to build llama.cpp server as a library

![image](https://github.com/user-attachments/assets/5c204569-f176-405e-9b1c-5fc39dec4863)

![image](https://github.com/user-attachments/assets/bb2b4f9b-6fd9-4666-a94d-2f65b1c7dd84)

**Comment by TC117** [comment]
Not show variant on Window like Linux
![Image](https://github.com/user-attachments/assets/feee7160-4e7d-4e90-a4d6-425252a1dae9)
Working on Linux
![Image](https://github.com/user-attachments/assets/27e2de24-fdc9-43ce-9d96-a38274634424)

Cant load model with cuda variant 
```
PS C:\WINDOWS\system32> cortex-nightly.exe run tinyllama
Starting server ...
Set log level to INFO
Host: 127.0.0.1 Port: 39281
Server started
API Documentation available at: http://127.0.0.1:39281
Model failed to start: Failed to load model
Error: Failed to start model
PS C:\WINDOWS\system32>
```

**Comment by vansangpfiev** [comment]
Specs changes:
- Move all OpenAI API compatibility from engine to cortex
- Spawn `llama-server` (maybe `llava` also) directly from cortex

Diagram:

![Image](https://github.com/user-attachments/assets/443a0598-38e6-4d3a-8797-312ed227952f)

Task list:

- [x] Fork of llama.cpp 
- [x] Engine management (Linux, Windows, macOS)
- [x] OpenAI API compatibility
- [x] CIs
- [x] Verify with QA checklists
- [ ] Docs

Engine variants:
- [x] ubuntu-arm64
- [x] linux-avx-cuda-cu11.7-x64
- [x] linux-avx-cuda-cu12.0-x64
- [x] linux-avx-x64
- [x] linux-avx2-cuda-cu11.7-x64
- [x] linux-avx2-cuda-cu12.0-x64
- [x] ubuntu-x64
- [x] linux-avx512-cuda-cu11.7-x64
- [x] linux-avx512-cuda-cu12.0-x64
- [x] linux-avx512-x64
- [x] linux-noavx-cuda-cu11.7-x64
- [x] linux-noavx-cuda-cu12.0-x64
- [x] linux-noavx-x64
- [x] ubuntu-vulkan-x64
- [x] macos-arm64
- [x] macos-x64
- [x] win-avx-cuda-cu11.7-x64
- [x] win-avx-cuda-cu12.0-x64
- [x] win-avx-x64
- [x] win-avx2-cuda-cu11.7-x64
- [x] win-avx2-cuda-cu12.0-x64
- [x] win-avx2-x64
- [x] win-avx512-cuda-cu11.7-x64
- [x] win-avx512-cuda-cu12.0-x64
- [x] win-avx512-x64
- [x] win-noavx-cuda-cu11.7-x64
- [x] win-noavx-cuda-cu12.0-x64
- [x] win-noavx-x64
- [x] win-vulkan-x64

In case of macOS, we'd like to support macos-12, then we implemented a filter for llama.cpp server in cortex

**Comment by dan-menlo** [comment]
- Can ship early next week

**Comment by vansangpfiev** [comment]
# QA-checklist

OS 
- [x] Windows 11
- [x] Ubuntu 24, 22
- [x] Mac Silicon OS 14/15 
- [ ] Mac Intel

Engine variant:
- [ ] ubuntu-arm64
- [ ] linux-avx-cuda-cu11.7-x64
- [ ] linux-avx-cuda-cu12.0-x64
- [ ] linux-avx-x64
- [ ] linux-avx2-cuda-cu11.7-x64
- [x] linux-avx2-cuda-cu12.0-x64
- [ ] ubuntu-x64
- [ ] linux-avx512-cuda-cu11.7-x64
- [ ] linux-avx512-cuda-cu12.0-x64
- [ ] linux-avx512-x64
- [ ] linux-noavx-cuda-cu11.7-x64
- [ ] linux-noavx-cuda-cu12.0-x64
- [ ] linux-noavx-x64
- [ ] ubuntu-vulkan-x64
- [x] macos-arm64
- [ ] macos-x64
- [ ] win-avx-cuda-cu11.7-x64
- [ ] win-avx-cuda-cu12.0-x64
- [ ] win-avx-x64
- [ ] win-avx2-cuda-cu11.7-x64
- [ ] win-avx2-cuda-cu12.0-x64
- [ ] win-avx2-x64
- [ ] win-avx512-cuda-cu11.7-x64
- [ ] win-avx512-cuda-cu12.0-x64
- [ ] win-avx512-x64
- [ ] win-noavx-cuda-cu11.7-x64
- [ ] win-noavx-cuda-cu12.0-x64
- [x] win-noavx-x64
- [ ] win-vulkan-x64

## Scope:
### CLI
Installation
- [x]  it should install with local installer (default; no internet required during installation, all dependencies bundled)
- [x]  it should install with network installer
- [x] it should install 2 binaries (cortex and cortex-server) [mac: binaries in `/usr/local/bin`]
- [x]  it should install with correct folder permissions
- [x]  it should install with folders: /engines /logs (no /models folder until model pull)
- [ ] It should install with Docker image https://cortex.so/docs/installation/docker/

Engine management:
- [x] llama.cpp should be installed by default
- [x] it should run gguf models on llamacpp
- [x] it should list engines
- [x] it should get engines
- [x] it should install engines (latest version if not specified)
- [x] it should install engines (with specified variant and version)
- [x] it should get default engine
- [x] it should set default engine (with specified variant/version)
- [x] it should load engine
- [x] it should unload engine
- [x] it should update engine (to latest version)
- [x] it should update engine (to specified version)
- [x] it should uninstall engines
- [x] it should gracefully continue engine installation if interrupted halfway (partial download)
- [x] it should gracefully handle when users try to CRUD incompatible engines (No variant found for xxx)

Model Running
- [x] `cortex run <cortexso model>` - if no local models detected, shows `pull` model menu
- [x] `cortex run` - if local model detected, runs the local model
- [x]  `cortex run` - if multiple local models detected, shows list of local models (from multiple model sources eg cortexso, HF authors) for users to select (via regex search)
- [x] `cortex run <invalid model id>` should return gracefully `Model not found!`
- [x]  run should autostart server
- [x] `cortex run <model>` starts interactive chat (by default)
- [x] `cortex run <model> -d` runs in detached mode
- [x] `cortex models start <model>`  
- [x] terminate StdIn or `exit()` should exit interactive chat

### API

Engine management
- [x] List engines: GET `/v1/engines`
- [x] Get engine: GET `/v1/engines/{name}`
- [x] Install engine: POST `/v1/engines/install/{name}`
- [x] Get default engine variant/version: GET `v1/engines/{name}/default`
- [x] Set default engine variant/version: POST `v1/engines/{name}/default`
- [x] Load engine: POST `v1/engines/{name}/load`
- [x] Unload engine: DELETE `v1/engines/{name}/load`
- [x] Update engine: POST `v1/engines/{name}/update`
- [x] uninstall engine: DELETE `/v1/engines/install/{name}`

Running Models
- [x] List models: GET `v1/models`
- [x] Start model: POST `/v1/models/start`
- [x] Stop model: POST `/v1/models/stop`
- [x] Get model: GET `/v1/models/{id}`
- [x] Delete model: DELETE `/v1/models/{id}`
- [x] Update model: PATCH `/v1/models/{model}` updates model.yaml params

### Additional requirements
- [x] Cortex spawns new child process when start a model
- [x] Cortex terminates child process when stop a model
- [x] Cortex terminates all child processes when it stops

**Comment by david-menloai** [comment]
testing completed, should be closed
