### ISSUE TITLE
roadmap: Cortex supports `/files`

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1786]
# Architecture for `files`:
- API should compatible and follow OpenAI: https://platform.openai.com/docs/api-reference/files

## Filesystem
```sh
~/cortexcpp
├── cortex.db
├── engines
├── files
│   └── Enterprise_Application_Infrastructure_v2_20140903_toCTC_v1.0.pdf
├── logs
├── models
└── threads
```

## Database
- File metadata will be stored in `files` table in `cortex.db`

## Backward compatible
Provide backward compatible for previous jan, which stores file inside each thread.
```json
./jan_1732370027
├── files
│   └── 01JDMG617BHMPW859VE18BPQ7Y.pdf
├── memory
│   ├── args.json
│   ├── docstore.json
│   └── hnswlib.index
├── messages.jsonl
└── thread.json
```

## Pros and Cons
- User can search for their file using their file name, we don't set their file name to any uuid like before.
- Easy to share files with assistants, tools, etc.

## API References
https://c6f778ad.cortex-docs.pages.dev/api-reference

**Comment by namchuai** [comment]
## Architecture for `files`:
- API should compatible and follow OpenAI: https://platform.openai.com/docs/api-reference/files

## Filesystem
```sh
~/cortexcpp
├── cortex.db
├── engines
├── files
├── 0001KNE06900GW0X476W5TVBFE
│   ├── AAPB2016_UIImplementation.pdf
│   └── metadata.json
├── 0001KNE3E500GW0X476W5TVBFE
│   ├── AAPB2016_UIImplementation.pdf
│   └── metadata.json
└── 0001KNE3EBC62D620DGYNG2R8H
    ├── AAPB2016_UIImplementation.pdf
    └── metadata.json
├── logs
├── models
└── threads
```
Sample `metadata.json`
```json
{
        "bytes" : 2099009,
        "created_at" : 1733755081,
        "filename" : "AAPB2016_UIImplementation.pdf",
        "id" : "0001KNE06900GW0X476W5TVBFE",
        "object" : "file",
        "purpose" : "assistant"
}
```
- User can search for their file using their file name, we don't set their file name to any uuid like before.
- Easy to share files with assistants, tools, etc.

## Backward compatible
We need to provide backward compatible for previous jan, which stores file inside each thread
```json
./jan_1732370027
├── files
│   └── 01JDMG617BHMPW859VE18BPQ7Y.pdf
├── memory
│   ├── args.json
│   ├── docstore.json
│   └── hnswlib.index
├── messages.jsonl
└── thread.json
```
Cortex will provide same API path as OpenAI's path, but requires additional property `thread_id` so that we can make cortex API compatible.

**Comment by namchuai** [comment]
Request for comment: Move the `metadata.json` to `cortex.db`

**Comment by dan-menlo** [comment]
## 12 Dec

- [x] Docs
- [x] Migration? -> Files table
- [x] Update Spec for this issue (for future reference)

**Comment by louis-jan** [comment]
Hi @dan-homebrew @namchuai, now that we’ve flattened the files under /files, which is more of a global storage, it’s not practical to keep the file name. Since file_search can be scoped to a thread or assistant, keeping the file name causes issues where duplicate file names are ignored, leading to incorrect behavior in most application

Case 1: 
- Users can have different files with the same name, they can't attach those to a thread.

Case 2:
- Users can upload the same file to a thread to update embeddings after model changes.

Case 3: 
- Reinforcing or weighting specific data - increase its weight in search results? In case they ingested multiple files before in the same thread.

Update 1: Attempting to add a postfix on duplicate

**Comment by TC117** [comment]
- [x] Can Upload files
![Image](https://github.com/user-attachments/assets/52b0a50a-6a71-41af-a005-7a7cc2f0ddf3)
![Image](https://github.com/user-attachments/assets/b1649f9b-7e7a-4bc1-abd2-d1f9e75787d4)

- [x] Can get files list
![Image](https://github.com/user-attachments/assets/8f4021b8-3bbd-4e55-843d-ead07068159f)

- [x] Get file with ID 
![Image](https://github.com/user-attachments/assets/fb9fe2bf-f740-4654-b7b5-e16456119735)

- [x] Get file content
![Image](https://github.com/user-attachments/assets/899e8359-9cd8-40fd-b584-3fc53fc77f47)

- [x] Delete file with ID
![Image](https://github.com/user-attachments/assets/2aba0757-1aad-4360-9754-d71ef54b2959)

Still need to check Backward compatible with Jan

**Comment by TC117** [comment]
Working with Jan
![Image](https://github.com/user-attachments/assets/5b6ca090-1644-48a4-8305-21b867bf6cd0)
![Image](https://github.com/user-attachments/assets/b0618b17-b5bd-4bbc-ba00-e18e1a3840b9)

But it will create _1 for files with the same name

**Comment by dan-menlo** [comment]
@namchuai @TC117 Please close this ticket if completed
