### ISSUE TITLE
roadmap: Cortex works on ARM-based SoCs (i.e. Raspberry Pi)

### ISSUE THREAD

**Issue by dan-menlo** [janhq/cortex.cpp#1789]
## Goal 

- Cortex should work on Raspberry Pi and ARM-based SoCs
- This will likely be the future direction for Cortex
- Likely Sprint 27

## Tasklist

- [x] Build cortex.cpp and cortex.llamacpp on linux arm64
- [x] What hardware is needed for this? 
  - Raspberry pi 5 for testing on real device: https://mlab.com.vn/raspberry-pi-5-mlab-com-vn
  - Orange pi 5 for testing on real device: https://orangepi.vn/shop/orange-pi-5-plus-32gb-ram
  - jetson xavier agx https://pivietnam.com.vn/nvidia-jetson-agx-xavier-developer-kit-deploy-ai-powered-autonomous-machines-at-scale-pivietnam-com-vn.html
  - More mac mini silicon to creat VM linux arm64 base for CICD agent
- [x] CI/CD pipeline
- [x] Update linux installation script by including arm64
- [x] Installation docs update

**Comment by hiento09** [comment]
Build cortex.cpp and cortex.llamacpp successfully but not able to run it
![Image](https://github.com/user-attachments/assets/daa22ccf-ff85-4e1b-a7e9-9b3dddcc2e5b)
![Image](https://github.com/user-attachments/assets/992c98a7-2e4f-4fdf-802a-a28f5268ec2b)
![Image](https://github.com/user-attachments/assets/25d205de-9634-4ef4-b510-88745a0764b3)
![Image](https://github.com/user-attachments/assets/0a4b8034-2725-41d8-a098-c9be642b34ad)

**Comment by hiento09** [comment]
![Image](https://github.com/user-attachments/assets/6704c636-8ca9-4821-8de7-6b85a03ac5c8)
![Image](https://github.com/user-attachments/assets/dbf5c86f-c8fc-4df8-ad26-a322ad9c330d)
![Image](https://github.com/user-attachments/assets/f9a4717b-9555-4fa1-abf9-fbb0b73808ec)
![Image](https://github.com/user-attachments/assets/5145ba8c-f0ba-48c9-b2be-9f850afe99fd)

cortex is able to run on orange pi 5

**Comment by hiento09** [comment]
![Image](https://github.com/user-attachments/assets/e4544b57-6b8f-4915-aae4-5c1ad3cf1124)
Macos silican can be create more than 2 VMs following this instruction https://khronokernel.com/macos/2023/08/08/AS-VM.html

**Comment by hiento09** [comment]
Orange pi 5
- Tinyllama: 4.69146374767 tokens per second
![Image](https://github.com/user-attachments/assets/931a6919-1ef2-477c-b1cf-8a82d545435c)
