### ISSUE TITLE
[Sub task]: Ichigo python wrapper server

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [janhq/cortex.cpp#1816]
**Problem**
- Cortex should support ichigo with 1 single endpoint
- When start ichigo, cortex should start all 3 models: ichigo llm, whisper vq, fish speech
- When stop ichigo, cortex should stop all 3 models: ichigo llm, whisper vq, fish speech
- Cortex should support realtime api: web socket?

**Task List**

- [x] cortex cpp: start all dependencies of ichigo wrapper through definition in model.yml, if 1 dep cannot start successfully, will stop all others depends.
- [ ] cortex cpp: Stop ichigo wrapper also stop all ichigo's dependencies
- [ ] Implement ichigo wrapper python server:
     - [x] Support non stream requests
     - [ ] Support stream requests (need to add implementation in cortex cpp to route streaming response)
     - [ ] Support realtime api (need to add implementation in cortex cpp to route web socket api)
- [ ] Package environment to run wrapper and test in 4 OS:
     - [ ] Linux
     - [ ] Windows
     - [ ] Mac ARM
     - [ ] Mac Intel
- [ ] Upload to hugging face
